language: python
python: 2.7
cache: pip
env:
  - TOX_ENV=py27
  - TOX_ENV=flake8
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.5
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=py36
